print("Enter an Adjective: ")
one = input()
print("Enter an Adjective: ")
two = input()
print("Enter a Type of Bird: ")
three = input()
print("Enter a Room in a House: ")
four = input()
print("Enter a past Tense Verb: ")
five = input()
print("Enter a Verb: ")
six = input()
print("Enter a relative's Name: ")
seven = input()
print("Enter a Noun: ")
eight = input()
print("Enter a Liquid: ")
nine = input()
print("Enter a Verb ending in -ing: ")
ten = input()
print("Enter a Part of the Body (plural): ")
eleven = input()
print("Enter a Plural Noun: ")
twelve = input()
print("Enter a Verb ending in -ing: ")
thirteen = input()
print("Enter a Noun: ")
fourteen = input()

print("It was a " + one + ", cold November day. \n I woke up to the " + two + " smell of " + three + "\n roasting in the " + four + " downstairs. \n I " + five + " down the stairs to see if I could \n help " + six + " the dinner. My mom said, \n \"See if " + seven + " needs a fresh " + eight + ".\" \n So I carried a tray of glasses full of " + nine + " into the " + ten + " room. When I got there, \n I couldn\'t believe my " + eleven + "! There were \n" + twelve + " " + thirteen + " on the " + fourteen + "!")